### ISSUE TITLE
REMOVE BIG Edtor Popup, Looks werid

### ISSUE THREAD

**Issue by radioblahaj** [waffleprogramming/waffleprogramming.github.io#12]

**Comment by AmazingMech2418** [comment]
This will not happen. It's fine. We can just change visibility settings to make it better.

**Comment by radioblahaj** [comment]
Yeah, but looks odd, make it in a new page

**Comment by AmazingMech2418** [comment]
I said we aren't doing it!

**Comment by radioblahaj** [comment]
Okay.
