### ISSUE TITLE
Need A Domain

### ISSUE THREAD

**Issue by radioblahaj** [waffleprogramming/waffleprogramming.github.io#3]

**Comment by AmazingMech2418** [comment]
How do we get a domain? I know how to get a <username>.github.io/<repository> domain but that's it.

**Comment by radioblahaj** [comment]
.com, .usa.cc ( I live in ca so, no) , .tk (free) do not  work.

**Comment by AmazingMech2418** [comment]
Really? It won't accept less than and greater than signs. Strange since this doesn't use HTML encoding (I think). Let's see. <a href="https://scratch.mit.edu">If this works, it should link to scratch.</a>

**Comment by radioblahaj** [comment]
YYup

**Comment by AmazingMech2418** [comment]
<script>alert("this is a test...");</script>

**Comment by AmazingMech2418** [comment]
Strange. It doesn't work for script tags... <p>paragraph test</p>

**Comment by radioblahaj** [comment]
What Are You Testing?
I can invest in a free js.org domain 
waffleprograming.js.org

**Comment by AmazingMech2418** [comment]
I was testing an HTML tag. Also, .js.org seems like a good domain.

**Comment by kerrtravers** [comment]
Going to close this and move all the domain conversation over to #4
