### ISSUE TITLE
Tracking Domain 

### ISSUE THREAD

**Issue by radioblahaj** [waffleprogramming/waffleprogramming.github.io#7]
Tracking Domain in  js-org/dns.js.org/1636
[Pull Request/Tracking in](https://github.com/js-org/dns.js.org/pull/1636)

**Comment by AmazingMech2418** [comment]
What is this for?

**Comment by radioblahaj** [comment]
Tracking the approval of .js.org DM name.

**Comment by kerrtravers** [comment]
It wasn't approved as we have no content on the page.

**Comment by radioblahaj** [comment]
We do, title

**Comment by kerrtravers** [comment]
"Before JS.ORG can accept a pull request there has to be "reasonable content" on the page (as stated in step 1 of the readme!). There has to be at least an index.html with some texts, links, images,... You should give anybody a clear picture what your page is (or will be) about.

This rule only exists to avoid name grabbing where people reserve one or more subdomains for later use but never put any content on the page. JS.ORG doesn't support this misbehaviour."

**Comment by AmazingMech2418** [comment]
So we have to get the project working before we can get a domain?

**Comment by kerrtravers** [comment]
Yeah
